name: ENV
on: push
env:
  USER_NAME: ${{secrets.USER_NAME}}
jobs:
  build:
   environment: dev
   env:
    LOCAL_USER_NAME: testing_localuser_name
   runs-on: ubuntu-latest
   steps:
    - name: print with direct
      run: echo $USER_NAME
    
    - name: print with context
      run: echo ${{env.USER_NAME}}
  
    - name: print local env
      run: echo ${{env.LOCAL_USER_NAME}}