name: Test ENV
on: push
env:
  USER_NAME: testing_username
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: print with direct
      run : echo $USER_NAME
    
    - name: print with context
      run: echo ${{env.USER_NAME}}
  