name: Resource1
on:
 workflow_call:
    inputs:
      test_input:
        type: string
        required: true
    secrets:
      test_secret:
        required: true
    outputs:
      result:
        value: ${{ jobs.test_build.outputs.result }}
    
jobs:
 test_build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.step1.outputs.value }}
    steps:
      - name: Print Details
        run: echo ${{inputs.test_input}} and ${{secrets.test_secret}}4

      - name: Set output
        id: step1
        run: echo "value=done" >> $GITHUB_OUTPUT